# Gêneros para os clientes
GENEROS_PESSOAS = ["Masculino", "Feminino", "Outro"]

# Estado Civil dos clientes
ESTADO_CIVIL = ["Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)"]

# Generos para os produtos
GENEROS_PRODUTOS = ["Masculino", "Feminino", "Unissex"]

# Marcas para os produtos
MARCAS = [
    "Nike",
    "Adidas",
    "Puma",
    "Mizuno",
    "Asics",
    "Vans",
    "Converse",
    "New Balance",
    "Reebok",
    "Olympikus",
]

# Modelos de tênis
MODELOS = {
    "Nike": [
        "Air Max",
        "Air Force 1",
        "Cortez",
        "Blazer",
        "React",
        "Zoom",
        "Pegasus",
        "VaporMax",
        "Free",
        "Shox",
    ],
    "Adidas": [
        "Ultraboost",
        "NMD",
        "Stan Smith",
        "Superstar",
        "Gazelle",
        "Samba",
        "Campus",
        "Adilette",
        "Yeezy",
        "Prophere",
    ],
    "Puma": [
        "Suede",
        "Clyde",
        "RS-X",
        "Future Rider",
        "Basket",
        "Roma",
        "Ignite",
        "Tazon",
        "Disc Blaze",
        "Cell",
    ],
    "Mizuno": [
        "Wave Rider",
        "Wave Inspire",
        "Wave Sky",
        "Wave Horizon",
        "Wave Ultima",
        "Wave Prophecy",
        "Wave Shadow",
        "Wave Equate",
        "Wave Enigma",
        "Wave Sayonara",
        "Wave Zonic",
    ],
    "Asics": [
        "Gel-Kayano",
        "Gel-Nimbus",
        "Gel-Cumulus",
        "Gel-Quantum",
        "Gel-DS Trainer",
        "Gel-Contend",
        "Gel-Pulse",
        "Gel-Venture",
        "Gel-Excite",
        "Gel-Fujitrabuco",
    ],
    "Vans": [
        "Old Skool",
        "Sk8-Hi",
        "Authentic",
        "Slip-On",
        "Era",
        "Chukka",
        "Half Cab",
        "Style 36",
        "Style 47",
        "UltraRange",
    ],
    "Converse": [
        "Chuck Taylor All Star",
        "One Star",
        "Jack Purcell",
        "Pro Leather",
        "Weapon",
        "Star Player",
        "All Star Pro BB",
        "Chuck 70",
        "Run Star Hike",
        "Cons",
    ],
    "New Balance": [
        "990",
        "574",
        "997",
        "1080",
        "Fresh Foam 1080",
        "FuelCell Rebel",
        "5740",
        "997H",
        "X90",
        "Made in USA 990v5",
    ],
    "Reebok": [
        "Classic Leather",
        "Club C",
        "Pump",
        "Nano",
        "Zig Kinetica",
        "Freestyle",
        "DMX Run",
        "Instapump Fury",
        "Sole Fury",
        "Aztrek",
    ],
    "Olympikus": [
        "Cosmic",
        "Pulsar",
        "Stellar",
        "Nebula",
        "Galaxy",
        "Meteor",
        "Orbit",
        "Comet",
        "Lunar",
        "Solar",
    ],
}

# Categorias para os produtos
CATEGORIAS = ["Casual", "Esporte", "Corrida", "Basquete", "Skate", "Social"]

# Cores para os produtos
CORES = [
    "Preto/Branco",
    "Azul/Branco",
    "Vermelho/Preto",
    "Preto/Vermelho",
    "Xadrez",
    "Rosa/Branco",
    "Branco/Azul",
    "Marrom",
    "Verde/Preto",
    "Roxo/Branco",
    "Amarelo/Preto",
    "Cinza/Branco",
    "Laranja/Preto",
    "Dourado/Preto",
]

# Métodos de pagamento
FORMA_PAGAMENTO = ["Cartão Crédito", "Cartão Débito", "PIX", "Boleto Bancário"]

# Status dos pedidos
STATUS_PEDIDO = ["Pendente", "Processando", "Enviado", "Entregue", "Cancelado"]

# E-mail marketing
EMAIL_MARKETING = ["Sim", "Não"]

ENTREGUE = ["Sim", "Não"]

# DDD telefônicos brasileiros
DDD_BR = [
    11,
    21,
    31,
    41,
    51,
    61,
    71,
    81,
    91,
    27,
    28,
    62,
    64,
    65,
    66,
    67,
    68,
    69,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    92,
    93,
    94,
    95,
    96,
    97,
    98,
    99,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    22,
    24,
    32,
    33,
    34,
    35,
    36,
    37,
    38,
    42,
    43,
    44,
    45,
    46,
    52,
    53,
    54,
    55,
    63,
]

# Estados - Cidade - Bairros brasileiros
CBE = {
    "BA": {
        "Salvador": [
            "Centro",
            "Barra",
            "Graça",
            "Ondina",
            "Pituba",
            "Itaigara",
            "Imbuí",
            "Stiep",
            "Costa Azul",
            "Brotas",
        ],
        "Feira de Santana": [
            "Centro",
            "Santa Mônica",
            "Muchila",
            "SIM",
            "Tomba",
            "Campo Limpo",
            "Brasília",
            "Queimadinha",
            "Mangabeira",
            "Papagaio",
        ],
    },
    "PE": {
        "Recife": [
            "Boa Viagem",
            "Pina",
            "Casa Forte",
            "Graças",
            "Espinheiro",
            "Derby",
            "Madalena",
            "Tamarineira",
            "Aflitos",
            "Cordeiro",
        ],
        "Olinda": [
            "Bairro Novo",
            "Casa Caiada",
            "Rio Doce",
            "Peixinhos",
            "Varadouro",
            "Amaro Branco",
            "Ouro Preto",
            "Jardim Atlântico",
            "Bultrins",
            "Sapucaia",
        ],
    },
    "CE": {
        "Fortaleza": [
            "Aldeota",
            "Meireles",
            "Varjota",
            "Cocó",
            "Papicu",
            "Montese",
            "Benfica",
            "Parangaba",
            "Fátima",
            "Cidade dos Funcionários",
        ],
        "Juazeiro do Norte": [
            "Centro",
            "Triângulo",
            "Pirajá",
            "Romeirão",
            "Lagoa Seca",
            "Salesianos",
            "Timbaúbas",
            "Novo Juazeiro",
            "Franciscanos",
            "Socorro",
        ],
    },
    "GO": {
        "Goiânia": [
            "Setor Bueno",
            "Setor Oeste",
            "Setor Marista",
            "Jardim Goiás",
            "Centro",
            "Campinas",
            "Setor Sul",
            "Pedro Ludovico",
            "Aeroporto",
            "Universitário",
        ],
        "Anápolis": [
            "Centro",
            "Jundiaí",
            "Vila Jaiara",
            "Recanto do Sol",
            "Alvorada",
            "Dom Felipe",
            "Industrial",
            "Maracanã",
            "São João",
            "Filostro Machado",
        ],
    },
    "PA": {
        "Belém": [
            "Batista Campos",
            "Umarizal",
            "Nazaré",
            "Reduto",
            "Marco",
            "Pedreira",
            "Jurunas",
            "Guamá",
            "Canudos",
            "Cremação",
        ],
        "Santarém": [
            "Centro",
            "Aldeia",
            "Prainha",
            "Santíssimo",
            "Fátima",
            "Interventoria",
            "Diamantino",
            "Mapiri",
            "Liberdade",
            "Caranazal",
        ],
    },
    "ES": {
        "Vitória": [
            "Praia do Canto",
            "Jardim da Penha",
            "Mata da Praia",
            "Centro",
            "Bento Ferreira",
            "Jucutuquara",
            "Santa Lúcia",
            "Enseada do Suá",
            "Ilha do Boi",
            "Ilha do Frade",
        ],
        "Vila Velha": [
            "Praia da Costa",
            "Itapuã",
            "Centro",
            "Coqueiral de Itaparica",
            "Glória",
            "Cobilândia",
            "Ibes",
            "Soteco",
            "Jardim Marilândia",
            "Santa Mônica",
        ],
    },
    "SC": {
        "Florianópolis": [
            "Centro",
            "Trindade",
            "Lagoa da Conceição",
            "Campeche",
            "Ingleses",
            "Estreito",
            "Córrego Grande",
            "Coqueiros",
            "Agronômica",
            "Itacorubi",
        ],
        "Joinville": [
            "Centro",
            "América",
            "Atiradores",
            "Anita Garibaldi",
            "Bucarein",
            "Iririú",
            "Saguaçu",
            "Glória",
            "Costa e Silva",
            "Floresta",
        ],
    },
    "MT": {
        "Cuiabá": [
            "Centro",
            "Goiabeiras",
            "Duque de Caxias",
            "Jardim das Américas",
            "CPA",
            "Pedra 90",
            "Boa Esperança",
            "Santa Rosa",
            "Araés",
            "Dom Aquino",
        ],
        "Rondonópolis": [
            "Centro",
            "Vila Aurora",
            "Parque Universitário",
            "Monte Líbano",
            "Jardim Atlântico",
            "Sagrada Família",
            "Cidade Alta",
            "Cohab",
            "Granville",
            "Colina Verde",
        ],
    },
    "AL": {
        "Maceió": [
            "Ponta Verde",
            "Jatiúca",
            "Pajuçara",
            "Farol",
            "Mangabeiras",
            "Benedito Bentes",
            "Trapiche",
            "Jaraguá",
            "Gruta",
            "Cruz das Almas",
        ],
        "Arapiraca": [
            "Centro",
            "Brasília",
            "Baixa Grande",
            "Primavera",
            "Canafístula",
            "Santa Esmeralda",
            "Eldorado",
            "Ouro Preto",
            "Itapoã",
            "Verdes Campos",
        ],
    },
    "PB": {
        "João Pessoa": [
            "Tambaú",
            "Manaíra",
            "Bessa",
            "Cabo Branco",
            "Altiplano",
            "Bancários",
            "Cristo",
            "Jaguaribe",
            "Centro",
            "Torre",
        ],
        "Campina Grande": [
            "Centro",
            "Catolé",
            "Bodocongó",
            "Alto Branco",
            "José Pinheiro",
            "Liberdade",
            "Prata",
            "Malvinas",
            "Cruzeiro",
            "Santa Rosa",
        ],
    },
    "RN": {
        "Natal": [
            "Ponta Negra",
            "Capim Macio",
            "Lagoa Nova",
            "Tirol",
            "Petrópolis",
            "Alecrim",
            "Cidade Alta",
            "Neópolis",
            "Igapó",
            "Ribeira",
        ],
        "Mossoró": [
            "Centro",
            "Nova Betânia",
            "Alto de São Manoel",
            "Doze Anos",
            "Abolição",
            "Santo Antônio",
            "Planalto 13 de Maio",
            "Aeroporto",
            "Boa Vista",
            "Redenção",
        ],
    },
    "SE": {
        "Aracaju": [
            "Atalaia",
            "Jardins",
            "13 de Julho",
            "Grageru",
            "Centro",
            "Siqueira Campos",
            "Aruana",
            "Farolândia",
            "São Conrado",
            "Coroa do Meio",
        ],
        "Itabaiana": [
            "Centro",
            "Marianga",
            "Miguel Teles",
            "Queimadas",
            "Porto",
            "Anízio Amâncio",
            "Bananeira",
            "São Cristóvão",
            "Oviêdo Teixeira",
            "Campo Grande",
        ],
    },
    "PI": {
        "Teresina": [
            "Centro",
            "Ininga",
            "Jóquei",
            "Fátima",
            "Ilhotas",
            "São Cristóvão",
            "Dirceu",
            "Buenos Aires",
            "Mocambinho",
            "Piçarra",
        ],
        "Parnaíba": [
            "Centro",
            "Nossa Senhora de Fátima",
            "Piauí",
            "São Benedito",
            "Catanduvas",
            "Reis Veloso",
            "Rodoviária",
            "Dirceu Arcoverde",
            "Planalto",
            "Nova Parnaíba",
        ],
    },
    "MA": {
        "São Luís": [
            "Calhau",
            "Renascença",
            "Cohama",
            "Turu",
            "Centro",
            "Anil",
            "Vinhais",
            "São Francisco",
            "Olho d'Água",
            "Angelim",
        ],
        "Imperatriz": [
            "Centro",
            "Bacuri",
            "Vila Nova",
            "Parque do Buriti",
            "Três Poderes",
            "Santa Rita",
            "Nova Imperatriz",
            "Juçara",
            "Cafeteira",
            "Vila Lobão",
        ],
    },
    "SP": {
        "São Paulo": [
            "Centro",
            "Pinheiros",
            "Vila Mariana",
            "Jardim Paulista",
            "Higienópolis",
            "Pinheiros",
            "Moema",
            "Vila Olímpia",
            "Brooklin",
            "Itaim Bibi",
        ],
        "Santos": [
            "Centro",
            "Praia do Forte",
            "Jardim das Oliveiras",
            "Vila Nova",
            "Praia Grande",
            "Cidade Nova",
            "Jardim América",
            "Vila Operária",
            "Praia do Sonho",
            "Vila do Bosque",
        ],
        "Campinas": [
            "Centro",
            "Jardim América",
            "Vila União",
            "Jardim das Flores",
            "Jardim Paulista",
            "Jardim das Nações",
            "Jardim das Palmeiras",
            "Jardim das Rosas",
            "Jardim das Violetas",
            "Jardim das Margaridas",
        ],
    },
    "RJ": {
        "Rio de Janeiro": [
            "Centro",
            "Copacabana",
            "Ipanema",
            "Leblon",
            "Jardim Botânico",
            "Tijuca",
            "Botafogo",
            "Barra da Tijuca",
            "Saúde",
            "Galeão",
        ],
        "Niterói": [
            "Centro",
            "Cidade Nova",
            "Praia de Niterói",
            "Jardim das Oliveiras",
            "Jardim das Palmeiras",
            "Jardim das Rosas",
            "Jardim das Violetas",
            "Jardim das Margaridas",
            "Jardim das Narcissos",
            "Jardim das Begônias",
        ],
    },
}

# Canais de venda
CANAIS_VENDA = ["Loja Física", "E-commerce", "Marketplace", "Telefone", "WhatsApp"]
